remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

title: Suleiman Sahawneh
description: Pricing analyst and incoming MS Business Analytics student at Cal State San Marcos.
baseurl: /practice-portfolio
url: https://suleimansahawneh2.github.io
repository: suleimansahawneh2/practice-portfolio

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: Suleiman Sahawneh
  avatar: /assets/img/logo.png
  bio: Pricing analytics, Python, SQL, Power BI.
  location: San Marcos, CA
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/suleimansahawneh2

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
